version: '2'
services:
  grafana_graphite:
    build: .
    image: kamon/grafana_graphite
    container_name: kamon-grafana-dashboard
    restart: on-failure
    ports:
      - '8000:80'
      - '8001:81'
      - '8125:8125/udp'
      - '8126:8126'
    volumes:
      - ./data/whisper:/opt/graphite/storage/whisper
      - ./data/grafana:/opt/grafana/data
      - ./log/graphite:/opt/graphite/storage/log
